name: main
on:
  push:
    paths-ignore:
      - "docs/"
    branches:
    - main
jobs:
  main:
    runs-on: ubuntu-24.04
    steps:
      - name: Install wget via apt
        run: sudo apt-get update -y && sudo apt-get install wget -y
      - name: Install chezmoi
        run: sudo sh -c "$(wget -qO- get.chezmoi.io)" -- -b /usr/local/bin
      - name: Setup dotfiles by chezmoi
        run: chezmoi init owlinux1000
      - name: Apply dotfiles
        run: chezmoi apply --dry-run
